includes:
  - "../pretrain/ernie.yml"

model_name: bert_for_classification

model_attributes:
    hidden_dropout_prob: 0.5
    initializer_range: 0.02
    hidden_size: 798

training:
#  policy:
#    name: "k-fold"
#    config:
#      k: 5
  learning_rate: 1e-5
  max_epochs: 10
  batch_size: 32

  callbacks:
    # callback name
    early_stopping:
      switch: false
      config:
        patience: 2
#    lr_finder:
#      switch: true
#
#  optimizer:
#    name: adam

  optimizer_wrappers:
    swa:
      switch: true
      config:
        start_epoch: 5
    lr_multiplier:
      switch: false
      config:
        multipliers:
          bert_for_qa/bert: 0.1

dataset:
  name: "dureader/yesno"
  data_dir: "./data"
  transformer: "dureader/yesno"

  source:
    train: "train + validation"
    validation: 'validation[:50%]'
    test: "validation[-50%:]"

  tokenizer:
    max_query_length: 64

  inputs:
    - name: input_ids
      column: input_ids
      type: LIST_OF_INT
      max_len: 512
    - name: token_type_ids
      column: segment_ids
      type: LIST_OF_INT
      max_len: 512
    - name: attention_mask
      column: input_mask
      type: LIST_OF_INT
      max_len: 512

  outputs:
    - name: output_1
      column: label
      type: CLASSLABEL
      num: 3
      labels: ['no', 'yes', 'depends']
      loss:
        name: sparse_categorical_crossentropy
        config:
          from_logits: true
      metrics:
        - name: sparse_categorical_accuracy

pretrained:
    name: ERNIE_1.0_max-len-512
    init_from_pretrained: true


