# config for bert wwm
includes:
  - "../base.yml"

dataset:
    tokenizer:
        name: bert_tokenizer
        vocab:
            filename: null
            special_tokens:
                PAD: "[PAD]"
                UNK: "[UNK]"
                SEP: "[SEP]"
                CLS: "[CLS]"
                MASK: "[MASK]"
        tokenize_chinese_chars: True
        do_lower_case: True
        do_basic_tokenize: True
        non_split_tokens: null
        max_len: 512

pretrained:
    norm_name: bert
    name: chinese_wwm
    adapter: tf_huggingface_bert_adapter
    force_download: false
    init_from_pretrained: true
    cache_dir: /search/odin/yyk/data/pretrained/bert # your path to save models
    model_path: null
    vocab_path: null
    config_path: null
    config:
        output_attentions: false
        output_hidden_states: false
        layer_norm_eps: 1e-12
    ref: https://github.com/ymcui/Chinese-BERT-wwm
    family:
        chinese_roberta_wwm_large_ext:
            model:
                # your/path/to/chinese_roberta_wwm_large_ext
                url: /search/odin/yyk/data/pretrained/bert/chinese_roberta_wwm_large_ext
                suffix: bert_model.ckpt
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                # your/path/to/chinese_roberta_wwm_large_ext/vocab.txt
                url: /search/odin/yyk/data/pretrained/bert/chinese_roberta_wwm_large_ext/vocab.txt
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                # your/path/to/chinese_roberta_wwm_large_ext/bert_config.json
                url: /search/odin/yyk/data/pretrained/bert/chinese_roberta_wwm_large_ext/bert_config.json
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config
        chinese_roberta_wwm_ext:
            model:
                # your/path/to/chinese_roberta_wwm_ext
                url: /search/odin/yyk/data/pretrained/bert/chinese_roberta_wwm_ext
                suffix: bert_model.ckpt
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                # your/path/to/chinese_roberta_wwm_ext/vocab.txt
                url: /search/odin/yyk/data/pretrained/bert/chinese_roberta_wwm_ext/vocab.txt
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                # your/path/to/chinese_roberta_wwm_ext/bert_config.json
                url: /search/odin/yyk/data/pretrained/bert/chinese_roberta_wwm_ext/bert_config.json
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config
        chinese_wwm_ext:
            model:
                # your/path/to/chinese_wwm_ext
                url: /search/odin/yyk/data/pretrained/bert/chinese_wwm_ext
                suffix: bert_model.ckpt
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                # your/path/to/chinese_wwm_ext/vocab.txt
                url: /search/odin/yyk/data/pretrained/bert/chinese_wwm_ext/vocab.txt
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                # your/path/to/chinese_wwm_ext/bert_config.json
                url: /search/odin/yyk/data/pretrained/bert/chinese_wwm_ext/bert_config.json
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config
        chinese_wwm:
            model:
                # your/path/to/chinese_wwm
                url: /search/odin/yyk/data/pretrained/bert/chinese_wwm
                suffix: bert_model.ckpt
                to_insert_paths:
                    - pretrained.model_path
            vocab:
                # your/path/to/chinese_wwm/vocab.txt
                url: /search/odin/yyk/data/pretrained/bert/chinese_wwm/vocab.txt
                to_insert_paths:
                    - pretrained.vocab_path
                    - dataset.tokenizer.vocab.filename
            config:
                # your/path/to/chinese_wwm/bert_config.json
                url: /search/odin/yyk/data/pretrained/bert/chinese_wwm/bert_config.json
                to_insert_paths: # set the pretrained.config_path with saved path of this file.
                    - pretrained.config_path
                to_replaces: # replace pretrained.config with the json content.
                    - pretrained.config

